### ISSUE TITLE
[BE] 프로젝트 개발 환경 구축 및 세팅

### ISSUE THREAD

**Issue by levhyun** [TW00D/letsgo-api-mini#1]
### Make Feature
none

### Todo
- [x] Pull Request 템플릿 추가
- [x] Prisma 세팅 + DB 연동
- [x] Env 서비스 구축
- [x] Cors 처리
- [x] Validate Config 추가
- [x] Exception 헨들러 구현
- [x] Logging 세팅
- [x] Response 세팅

### Estimated Time
~2023.03.15
