### ISSUE TITLE
[FEAT] 협업 환경 구축

### ISSUE THREAD

**Issue by levhyun** [TW00D/letsgo-api-mini#12]
## 어떤 기능입니까?
협업 개발을 위한 서비스 인터페이스 구축 및 모델과 DTO 구현

## TODO
- [x] user, category, post, comment 모델 작성 및 연관관계 매핑
- [x] 요청 DTO 구현
- [x] 서비스 인터페이스 구축

## 데드라인
2024/03/21 13:30 ~ 2024/03/23 13:00

## 기타 사항
내용 없음
