### ISSUE TITLE
[BE] 회원가입 구현

### ISSUE THREAD

**Issue by levhyun** [TW00D/letsgo-api-mini#3]
### Make Feature
- 회원가입 구현

### Todo
- [x] Prisma에 User Model 작성
- [x] User Model 작성
- [x] 회원가입 로직 구현

### Estimated Time
~2023.03.16
